repos:
-   repo: https://github.com/sirwart/ripsecrets.git
    # Set your version, be sure to use the latest and update regularly or use 'main'
    #rev: v0.1.5
    rev: main
    hooks:
    # use this one when you have a rust environment available
    -   id: ripsecrets
    # use this one when you will install ripsecrets with a package manager
    # -   id: ripsecrets-system
